### ISSUE TITLE
做这个商业版挣钱不，我可以加入的

### ISSUE THREAD

**Issue by xx-zhang** [jx-sec/jxwaf-mini-server#1]
我担任过国内前5的公司的安全研究员(两年)。我曾负责过基于 modsecruity 二次开发waf, 对modsecurity的机制优化，魔改等非常熟悉，你这个 nginx_lua_waf 我一看就知道什么回事儿。

另外我熟悉的领域。
- django2/python3 
- docker / k8s 
- vagrant / kvm / virtulbox 
- 安全运营

**Comment by xiaochao** [comment]
> 我担任过国内前5的公司的安全研究员(两年)。我曾负责过基于 modsecruity 二次开发waf, 对modsecurity的机制优化，魔改等非常熟悉，你这个 nginx_lua_waf 我一看就知道什么回事儿。
> 
> 另外我熟悉的领域。
> 
> * django2/python3
> * docker / k8s
> * vagrant / kvm / virtulbox
> * 安全运营

有没有兴趣来我司做 modsecurity 二开，公司自研使用。
